//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_TPA_AN.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advertisement
    {
        public int AdvertisementID { get; set; }
        public int EmployeeID { get; set; }
        public string AdvertisementDescription { get; set; }
        public string AdvertisementStatus { get; set; }
        public System.DateTime Deadline { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
