//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_TPA_AN.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attraction
    {
        public int AttractionID { get; set; }
        public string AttractionName { get; set; }
        public string AttractionDescription { get; set; }
        public string AttractionHowToWork { get; set; }
        public string AttractionParticipant { get; set; }
        public System.DateTime AttractionStartDate { get; set; }
        public string AttractionStatus { get; set; }
    }
}
