//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_TPA_AN.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FundRequest
    {
        public int FundId { get; set; }
        public int FundPrice { get; set; }
        public string FundReason { get; set; }
        public int DepartmentID { get; set; }
        public string FundStatus { get; set; }
        public System.DateTime FundRequestedDate { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
