//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_TPA_AN.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ride
    {
        public int RideID { get; set; }
        public string RideName { get; set; }
        public string RideDescription { get; set; }
        public string RideHowToWork { get; set; }
        public string RideType { get; set; }
        public string RideSafetyInformation { get; set; }
        public string RideStatus_ { get; set; }
    }
}
