//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_TPA_AN.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketTransaction
    {
        public int TicketTransactionID { get; set; }
        public int Quantity { get; set; }
        public System.DateTime TicketDate { get; set; }
        public string TransactionStauts { get; set; }
    }
}
